### ISSUE TITLE
Test result panel not showing correct output

### ISSUE THREAD

**Issue by chedaroo** [shreifelagamy/vscode-pestphp#1]
## Expected Behaviour

Passing tests are rendered green in Testing Explorer and Test Results panel 

## Current Behaviour

Some are and some aren't, but they do all pass.  When I run test with pest CLI in terminal all pass and are rendered correctly.

<img width="1350" alt="Screenshot 2024-07-02 at 11 50 52" src="https://github.com/shreifelagamy/vscode-pestphp/assets/3003877/66f6cbad-904f-4172-85a9-83c070c18678">

**Comment by chedaroo** [comment]
Also, kudos on the project 🥇  !!!

**Comment by shreifelagamy** [comment]
@chedaroo Will check it and try to fix soon, appreciate your support 🙏

**Comment by chedaroo** [comment]
No prob's, flagging stuff is the easy bit.

It appears to be happening when chaining methods like 'with' and also with 'dataset' methods.

You can reproduce with the following tests:

```php

// Fine
it('is true', function () {
    expect(true)->toBe(true);
});

// No output
it('is true with', function (bool $bool) {
    expect($bool)
        ->toBe(true);
})->with([true, false]);

// Output but incorrect
it('is true with a dataset', function (bool $bool) {
    expect($bool)
        ->toBe(true);
})->with('data');

dataset('data', [true, false]);
```
<img width="1351" alt="Screenshot 2024-07-02 at 12 23 17" src="https://github.com/shreifelagamy/vscode-pestphp/assets/3003877/a4b5c7bd-05b1-46a7-ac0a-f52246a1b230">

**Comment by shreifelagamy** [comment]
@chedaroo datasets are now supported in v1.1.0, Please check it and let me know if you are facing any issues

I will close this one, but feel free to open new ones if you faced any issues.

don't forget to stare and rate the extension 🙏 👍
